#!/bin/sh

# sudo=doas \
alias \
	cat='bat -n' \
    gitd='/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME' \
	grep='grep --color --exclude-dir={.bzr,CVS,.git,.hg,.svn}' \
	ls='exa -al --color=always --group-directories-first' \
	pacman='doas pacman' \
	p='doas pacman -S' \
	rm='trash-put' \
    vimu='~/sources/neovim/build/bin/nvim -u NONE' \
    wget=wget --hsts-file="$XDG_STATE_HOME/wget-hsts" \
	ytd="yt-dlp -f 'bv[height<=1080][ext=mp4]+ba'" \
	apt="sudo apt"\
