#! /bin/bash
# Use the provided interface, otherwise the device used for the default route.
if [[ -n $BLOCK_INSTANCE ]]; then
  IF=$BLOCK_INSTANCE
else
  IF=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------

if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo "" # full text
  echo "" # short text
#  echo \#FF0000 # color
  exit
elif [[ "$BLOCK_INSTANCE" = 'wlp2s0' ]]; then
  echo ""
  echo "WIFI"
  echo \#FFFFFF
elif [[ "$BLOCK_INSTANCE" = 'enp3s0' ]]; then
  echo "ETH"
  echo "ETH"
  echo \#FFFFFF
fi

